id: values_time
category_id: ai__input_dataset
title:
  - locale: en
    value: Values / Time
  - locale: fr
    value: Valeurs / Temps
description:
  - locale: en
    value: Measurements that are collected at regular intervals over a period of time.
  - locale: fr
    value: Mesures recueillies à intervalles réguliers sur une période de temps donnée.
citation: []
symbol_id: values_time
variables: []
