dtpr_id: values_time
category:
  - data_flow
name:
  en: Values / Time
  fr: Valeurs / Temps
description:
  en: Measurements that are collected at regular intervals over a period of time.
  fr: Mesures recueillies à intervalles réguliers sur une période de temps donnée.
icon: /dtpr-icons/values_time.svg
symbol: /dtpr-icons/symbols/values_time.svg
updated_at: 2025-08-29T00:00:00.000Z
