local_backend: true

backend:
  name: git-gateway

publish_mode: editorial_workflow

i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_folders

  # Required - a list of locales to show in the editor UI
  locales: [en, fr, es, pt, km, tl]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: en

# Media
media_folder: "public/dtpr-icons"
public_folder: "/dtpr-icons"

collections:
  - name: "datachain_types"
    i18n: true
    label: "Datachain Types" # Used in the UI
    slug: "{{id}}"
    folder: "content/dtpr.beta/datachain_types" # The path to the folder where the documents are stored
    fields:
      - {label: "ID", name: "id", widget: "string", i18n: "duplicate"}
      - {label: "Name", name: "name", widget: "string", i18n: true}
  - name: "categories" # Used in routes, e.g., /admin/collections/blog
    i18n: true
    label: "Category" # Used in the UI
    slug: '{{id}}'
    folder: "content/dtpr.beta/categories" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    identifier_field: name
    summary: "{{datachain_type}} – {{name}}"
    fields: # The fields for each document, usually in front matter
      - {label: "ID", name: "id", widget: "string", i18n: "duplicate"}
      - {label: "Name", name: "name", widget: "string", i18n: true}
      - {label: "Description", name: "description", widget: "string", i18n: true, required: false}
      - {label: "Question", name: "question", widget: "string", i18n: true, required: false}
      - label: "Datachain Types"
        name: "datachain_type"
        widget: "relation"
        collection: "datachain_types"
        value_field: "id"
        search_fields: ["name", "id"]
        display_fields: ["name"]
        i18n: "duplicate"
      # - label: "Element Context"
      #   name: "element_color_context"
      #   widget: "list"
      #   fields:
      #     - label: "Value"
      #       name: "value"
      #       widget: "string"
      #       i18n: "duplicate"
      #     - label: "Label"
      #       name: "label"
      #       widget: "string"
      #       i18n: true
      #     - label: "Description"
      #       name: "description"
      #       widget: "string"
      #       i18n: true
      #     - label: "Color"
      #       name: "color"
      #       widget: "string"
      #       i18n: "duplicate"
      - label: "Element Variables"
        name: "element_variables"
        widget: "list"
        i18n: true
        fields:
          - label: "ID"
            name: "id"
            widget: "string"
            i18n: "duplicate"
          - label: "Label"
            name: "label"
            widget: "string"
            i18n: true
          - label: "Required"
            name: "required"
            required: false
            widget: "boolean"
            i18n: "duplicate"
          - label: "Default"
            required: false
            name: "default"
            widget: "string"
            i18n: "duplicate"
  - name: "elements" # Used in routes, e.g., /admin/collections/blog
    i18n: true
    label: "Element" # Used in the UI
    folder: "content/dtpr.beta/elements" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    identifier_field: name
    slug: '{{category}}__{{id}}'
    summary: "{{category}} – {{name}}"
    view_groups:
      - label: "Category"
        field: category
    fields: # The fields for each document, usually in front matter
      - label: "Category"
        name: "category"
        widget: "relation"
        collection: "categories"
        value_field: "id"
        search_fields: ["name", "id"]
        display_fields: ["datachain_type", "name"]
        i18n: "duplicate"
        multiple: true
      - {label: "Name", name: "name", widget: "string", i18n: true}
      - {label: "ID", name: "id", widget: "string", i18n: "duplicate"}
      - {label: "Description", name: "description", widget: "markdown", i18n: true}
      - {label: "References", name: "references", widget: "markdown", i18n: true, required: false}
      - label: "Icon"
        name: "icon"
        widget: "image"
        choose_url: false
        allow_multiple: false
        i18n: "duplicate"
  
