// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/categories/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categories/[id].get').default>>>>
    }
    '/api/categories': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categories/index.get').default>>>>
    }
    '/api/elements/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/elements/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/elements/[id].put').default>>>>
    }
    '/api/elements': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/elements/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/elements/index.post').default>>>>
    }
    '/api/gaps': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/gaps/index.get').default>>>>
    }
    '/api/git/commit': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/git/commit.post').default>>>>
    }
    '/api/git/status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/git/status.get').default>>>>
    }
    '/api/icons/generate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/icons/generate.post').default>>>>
    }
    '/api/icons': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/icons/index.get').default>>>>
    }
    '/api/translate/batch': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/translate/batch.post').default>>>>
    }
    '/api/translate/single': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/translate/single.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../node_modules/.pnpm/@nuxt+nitro-server@4.3.1_better-sqlite3@12.6.2_db0@0.3.4_better-sqlite3@12.6.2__ioredis_c34745e21582d9757d743fd611dbc983/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../node_modules/.pnpm/@nuxt+icon@1.15.0_magicast@0.5.2_vite@7.3.1_@types+node@25.3.3_jiti@1.21.7_lightningcss_94d95d5b2421a683a93ebe13104988bb/node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
  }
}
export {}