import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import { mkdtemp, readFile, readdir, rm } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import { tmpdir } from 'node:os'
import { fileURLToPath } from 'node:url'
import { bundleSkills, rewriteReferenceCitations } from '../../cli/lib/skill-bundler.ts'
import { bundleSkillsCmd } from '../../cli/commands/bundle-skills.ts'

/**
 * Node-runner tests for the skill-bundler — verifies citation rewrite,
 * the generated TS module shape, and parity with the live
 * `plugin/dtpr/` source tree. Runs under the standard vitest
 * (vitest.cli.config.ts) so it can read the real plugin checkout.
 */

const REPO_ROOT = resolve(fileURLToPath(new URL('../../..', import.meta.url)))
const PLUGIN_ROOT = join(REPO_ROOT, 'plugin', 'dtpr')

let outDir: string

beforeAll(async () => {
  outDir = await mkdtemp(join(tmpdir(), 'dtpr-bundle-test-'))
})

afterAll(async () => {
  if (outDir) await rm(outDir, { recursive: true, force: true })
})

describe('rewriteReferenceCitations', () => {
  it('rewrites plugin/dtpr/references/<slug>.md citations to MCP prompt names', () => {
    const input =
      'Read `plugin/dtpr/references/comprehension-rubric.md` for the criteria and `plugin/dtpr/references/comprehension-block-template.md` for the shape.'
    const out = rewriteReferenceCitations(input)
    expect(out).toContain('`dtpr-references-comprehension-rubric`')
    expect(out).toContain('`dtpr-references-comprehension-block-template`')
    expect(out).not.toContain('plugin/dtpr/references/')
  })

  it('leaves unrelated paths intact', () => {
    const input =
      'Reads `plugin/dtpr/research/INDEX.md` and writes `app/public/dtpr-icons/symbols/<symbol_id>.svg`.'
    const out = rewriteReferenceCitations(input)
    expect(out).toBe(input)
  })

  it('is idempotent (a second rewrite is a no-op)', () => {
    const input = 'Read `plugin/dtpr/references/comprehension-rubric.md`.'
    const once = rewriteReferenceCitations(input)
    const twice = rewriteReferenceCitations(once)
    expect(twice).toBe(once)
  })
})

describe('bundleSkills', () => {
  it('emits one prompt per skill directory plus one per reference file', async () => {
    const outputPath = join(outDir, 'skills.test.generated.ts')
    const result = await bundleSkills({ pluginRoot: PLUGIN_ROOT, outputPath })

    const skillDirents = await readdir(join(PLUGIN_ROOT, 'skills'), { withFileTypes: true })
    const skillNames = skillDirents
      .filter((d) => d.isDirectory() && !d.name.startsWith('.'))
      .map((d) => d.name)
      .sort()

    const refDirents = await readdir(join(PLUGIN_ROOT, 'references'), { withFileTypes: true })
    const refSlugs = refDirents
      .filter((d) => d.isFile() && d.name.endsWith('.md'))
      .map((d) => d.name.replace(/\.md$/, ''))
      .sort()

    const promptNames = result.prompts.map((p) => p.name).sort()
    const expected = [
      ...skillNames,
      ...refSlugs.map((s) => `dtpr-references-${s}`),
    ].sort()
    expect(promptNames).toEqual(expected)
  })

  it('preserves SKILL.md frontmatter inside the bundled body', async () => {
    const outputPath = join(outDir, 'skills.test2.generated.ts')
    const result = await bundleSkills({ pluginRoot: PLUGIN_ROOT, outputPath })
    const elementDesign = result.prompts.find((p) => p.name === 'dtpr-element-design')
    expect(elementDesign).toBeDefined()
    expect(elementDesign!.body).toMatch(/^---\nname: dtpr-element-design\n/)
    expect(elementDesign!.body).toContain('description:')
    // Reference citations are rewritten in the bundled body.
    expect(elementDesign!.body).not.toContain('plugin/dtpr/references/')
  })

  it('truncates the prompts/list description to <=240 chars', async () => {
    const outputPath = join(outDir, 'skills.test3.generated.ts')
    const result = await bundleSkills({ pluginRoot: PLUGIN_ROOT, outputPath })
    for (const p of result.prompts) {
      expect(p.description.length).toBeGreaterThan(0)
      expect(p.description.length).toBeLessThanOrEqual(240)
    }
  })

  it('emits a parseable TS module that exports BUNDLED_PROMPTS', async () => {
    const outputPath = join(outDir, 'skills.test4.generated.ts')
    await bundleSkills({ pluginRoot: PLUGIN_ROOT, outputPath })
    const written = await readFile(outputPath, 'utf8')
    expect(written).toMatch(/AUTOGENERATED/)
    expect(written).toMatch(/export const BUNDLED_PROMPTS/)
    // Every entry has the expected three-key shape.
    expect(written).toMatch(/name:/)
    expect(written).toMatch(/description:/)
    expect(written).toMatch(/body:/)
  })
})

describe('bundleSkillsCmd', () => {
  it('writes to the requested output path and reports the prompt count', async () => {
    const outputPath = join(outDir, 'cmd.test.generated.ts')
    const logs: string[] = []
    const result = await bundleSkillsCmd({
      pluginRoot: PLUGIN_ROOT,
      outputPath,
      log: (line) => logs.push(line),
    })
    expect(result.ok).toBe(true)
    expect(result.promptCount).toBeGreaterThan(0)
    expect(result.outputPath).toBe(outputPath)
    expect(logs.some((l) => l.includes('Bundling skills from'))).toBe(true)
    expect(logs.some((l) => l.includes('dtpr-describe-system'))).toBe(true)
  })
})

describe('drift detection', () => {
  it('committed src/mcp/prompts/skills.generated.ts matches the live plugin source', async () => {
    const generatedPath = join(REPO_ROOT, 'api', 'src', 'mcp', 'prompts', 'skills.generated.ts')
    const committed = await readFile(generatedPath, 'utf8')

    const fresh = join(outDir, 'drift-check.generated.ts')
    await bundleSkills({ pluginRoot: PLUGIN_ROOT, outputPath: fresh })
    const regenerated = await readFile(fresh, 'utf8')

    if (committed !== regenerated) {
      throw new Error(
        'src/mcp/prompts/skills.generated.ts is stale. Run `pnpm --filter ./api bundle:skills` and commit the result.',
      )
    }
  })
})
