# File: .github/workflows/pull-request.yml
name: Pull Request Workflow
on:
  pull_request:
    branches: [main]
jobs:
  create-discussion:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        id: vars
        run: |
          echo "::set-output name=pr_title::${{ github.event.pull_request.title }}"
          echo "::set-output name=pr_body::${{ github.event.pull_request.body }} (Link: ${{ github.event.pull_request.html_url }})"
      - name: Run curl command
        run: |
          curl -H "Authorization: bearer ${{secrets.BEARER_TOKEN}}" -X POST -d " {
            \"query\": \"mutation {
              createDiscussion(
                input: {repositoryId: \\\"R_kgDOHibgUQ\\\", categoryId: \\\"DIC_kwDOHibgUc4Cbmpw\\\", body: \\\"${{ steps.vars.outputs.pr_body }}\\\", title: \\\"${{ steps.vars.outputs.pr_title }}\\\"}
              ) {
                discussion {
                  id
                }
              }
            }\"
          }" https://api.github.com/graphql
